# Generated by Django 5.0.2 on 2024-03-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatheraws1mobservation',
            name='stnId',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='weatheraws1mobservation',
            name='tmKst',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='weatheraws1mobservation',
            name='tmKstStn',
            field=models.CharField(max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weatherawsstninfo',
            name='stnId',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='weatherawsstninfo',
            name='stnIdKO',
            field=models.CharField(max_length=70, primary_key=True, serialize=False),
        ),
    ]
