# Generated by Django 4.1.5 on 2024-03-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_weatheraws1mobservation_stnid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airqualitygrade',
            name='air_quality_info',
        ),
        migrations.DeleteModel(
            name='ApiResponse',
        ),
        migrations.RemoveField(
            model_name='finedustgrade',
            name='forecast',
        ),
        migrations.DeleteModel(
            name='MidTermLandForecast',
        ),
        migrations.DeleteModel(
            name='MidTermTemperature',
        ),
        migrations.DeleteModel(
            name='SidoRealTimeAirQuality',
        ),
        migrations.DeleteModel(
            name='SunriseSunset1',
        ),
        migrations.DeleteModel(
            name='WeatherAlertForecast',
        ),
        migrations.DeleteModel(
            name='WeatherAws1Mobservation',
        ),
        migrations.DeleteModel(
            name='WeatherAwsStnInfo',
        ),
        migrations.DeleteModel(
            name='WeatherMidTermLandStatusForecast',
        ),
        migrations.DeleteModel(
            name='WeatherMidTermLandTempForecast',
        ),
        migrations.DeleteModel(
            name='WeatherShtTermCode',
        ),
        migrations.DeleteModel(
            name='WeatherShtTermLandForecast',
        ),
        migrations.DeleteModel(
            name='WeatherShtTermOceanForecast',
        ),
        migrations.DeleteModel(
            name='AirQualityForecast',
        ),
        migrations.DeleteModel(
            name='AirQualityGrade',
        ),
        migrations.DeleteModel(
            name='FineDustGrade',
        ),
        migrations.DeleteModel(
            name='WeeklyAirQualityForecast',
        ),
    ]
